#===========================
# Application
#===========================
spring.application.name=oms

#===========================
# Database
#===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/oms
spring.datasource.username=oms
spring.datasource.password=oms123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Let Spring Modulith JDBC create the official event_publication table schema.
# This avoids Hibernate creating varchar(255) columns that are too small for serialized events.
spring.modulith.events.jdbc.schema-initialization.enabled=true

#===========================
# Exception Messages
#===========================
spring.mvc.problemdetails.enabled=true

spring.messages.encoding=UTF-8
spring.messages.use-code-as-default-message=true
spring.messages.basename=\
  exception_messages/reservations_ex_messages,\
  exception_messages/orders_ex_messages,\
  exception_messages/tables_ex_messages,\
  exception_messages/common_ex_messages

#===========================
# Threading
#===========================
spring.threads.virtual.enabled=true

#===========================
# Spring Modulith Events
#===========================
spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.completion-mode=update